DROP TABLE listar_alumnos;
DROP TABLE listar_docentes;
CREATE VIEW listar_docentes AS select p.id_persona, p.cedula, p.primer_nombre,p.segundo_nombre, p.primer_apellido, p.segundo_apellido, p.correo, p.direccion, p.fecha_nac, p.telefono, d.titulo, d.area, d.abrev_titulo, c.nombre as "carrera" from persona p, docente d, carreras c where p.id_persona=d.id_persona and d.id_carrera=c.id_carrera;
CREATE VIEW listar_alumnos AS select p.id_persona, p.cedula, p.primer_nombre,p.segundo_nombre, p.primer_apellido, p.segundo_apellido, p.correo, p.direccion, p.fecha_nac, p.telefono, a.ciclo, a.paralelo, a.promedio, c.nombre as "carrera" from persona p, alumno a, carreras c where p.id_persona=a.id_persona and a.id_carrera=c.id_carrera;
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0150287671', 'aaa@gmail.com','Monay','2000-11-10','AGUILAR','KEVIN','LITUMA','VINICIO','0991663079');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('1723489742', 'bbb@gmail.com','Monay','2002-11-10','AGUILAR','XIMENA','LITUMA','MARIANA','0962381723');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('1234567893', 'ccc@gmail.com','Biblian','2001-1-2','LOPEZ','KATHERINE','LIMA','ANA','0962538361');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('1112233454', 'ddd@gmail.com','San Jose','2002-2-5','ROMERO','ANDREA','LITUMA','INES','0991456789');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('8746380945', 'eee@hotmail.com','Rosario','2002-11-10','AGUILAR','ANDRES','SUAREZ','LUIS','0991663079');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('9846382766', 'fff@hotmail.com','Monay','2000-11-10','PAZ','MARLENE','SUAREZ','ANDREA','0991663079');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('1827364597', 'ggg@gmail.com','Cuenca','2000-11-10','ANDRADE','ALEXANDER','SUAREZ','VINICIO','0972537281');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('9736485768', 'hhh@gmail.com','Valle','2001-11-10','AREVALO','MARIA','LOPEZ','ANA','0968364123');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('9273649179', 'iii@gmail.com','Cochapamba','2002-1-2','SALINA','PEDRO','LUNA','JUAN','0975382712');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0273947110', 'jjj@gmail.com','Miraflores','2003-2-5','ORTIZ','ROSA','SANTOS','ZOILA','0972381923');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0184628411', 'kkk@hotmail.com','Monay','2001-11-10','CUEVA','MARLON','APA','KEVIN','0963482345');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0142738412', 'lll@hotmail.com','Ricaurte','2002-11-10','NIEVES','KARLA','SUAREZ','ANDREA','0961523456');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('8372839413', 'mmm@gmail.com','El Valle','2002-11-10','LOPEZ','MARIO','PENALOZA','VINICIO','0982645283');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0927346114', 'nnn@gmail.com','Cuenca','2002-9-10','ANGAMARCA','SANDRA','ROBLES','EMILIA','0962962812');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0192734615', 'ooo@gmail.com','San Bartolo','2000-10-2','ASENCIO','ODALIS','IBARRA','GEOVANNA','0981723456');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0192739116', 'ppp@gmail.com','San Jose','2002-2-5','CASTILLO','DANIELA','COELLO','LUCIA','0912347234');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0192734517', 'qqq@hotmail.com','Ricaurte','2003-4-10','RAMIREZ','CARLA','SOLIS','SOFIA','0951423412');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0192749318', 'rrr@hotmail.com','Totoracocha','2001-6-10','ROMERO','ALBA','SANTANA','MARTINA','0991528172');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0188734519', 'sss@gmail.com','El Arenal','2000-6-10','MORENO','SARA','PINCAY','JULIA','0918273172');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0182652920', 'ttt@gmail.com','Santa Ana','2002-7-10','MULLER','CARMEN','AVILA','PAULA','0927391630');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0192436221', 'uuu@gmail.com','Chilcapamba','2001-11-2','PENALOZA','LARA','BRIONES','VALERIA','0927430271');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0182334122', 'vvv@gmail.com','El Vado','2002-2-5','ORTIZ','MIA','MERA','EMMA','0992538101');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0182462723', 'www@hotmail.com','Vergel','2000-11-10','PINOS','OLIVIA','PALACIOS','KEVIN','0973194721');
INSERT INTO public.persona( cedula, correo, direccion, fecha_nac, primer_apellido, primer_nombre, segundo_apellido, segundo_nombre, telefono) VALUES ('0182534824', 'xx@hotmail.com','Sidcay','2000-1-10','ARGUDO','CASANDRA','HERAS','MONICA','0917253910');
INSERT INTO public.carreras(abreviatura, modalidad, nombre) VALUES ('TSDS','PRESENCIAL','DESARROLLO DE SOFTWARE');
INSERT INTO public.carreras(abreviatura, modalidad, nombre) VALUES ('TSED','PRESENCIAL','ENTRENAMIENTO DEPORTIVO');
INSERT INTO public.carreras(abreviatura, modalidad, nombre) VALUES ('TSSP','DUAL','ELECTRICIDAD');
INSERT INTO public.carreras(abreviatura, modalidad, nombre) VALUES ('TSAS','PRESENCIAL','DESARROLLO DE SOFTWARE');
INSERT INTO public.alumno(ciclo, paralelo, promedio, id_carrera, id_persona) VALUES ('B','M5B',10,1,1);
INSERT INTO public.alumno(ciclo, paralelo, promedio, id_carrera, id_persona) VALUES ('A','MAB',9,1,2);
INSERT INTO public.alumno(ciclo, paralelo, promedio, id_carrera, id_persona) VALUES ('A','MAB',6,1,3);
INSERT INTO public.alumno(ciclo, paralelo, promedio, id_carrera, id_persona) VALUES ('B','MAB',9,1,4);
INSERT INTO public.alumno(ciclo, paralelo, promedio, id_carrera, id_persona) VALUES ('B','M5B',7,1,5);
INSERT INTO public.docente(abrev_titulo, area, titulo, id_carrera, id_persona) VALUES ('Ing', 'TICS', 'Ingeniero', 1, 6);
INSERT INTO public.docente(abrev_titulo, area, titulo, id_carrera, id_persona) VALUES ('Mgtr', 'Ciberseguridad', 'Magister', 1, 7);
INSERT INTO public.docente(abrev_titulo, area, titulo, id_carrera, id_persona) VALUES ('Tec', 'Calentamientos', 'Tecnologo', 2, 8);
INSERT INTO public.docente(abrev_titulo, area, titulo, id_carrera, id_persona) VALUES ('Lic', 'Crossfit', 'Licenciado', 2, 9);
INSERT INTO public.docente(abrev_titulo, area, titulo, id_carrera, id_persona) VALUES ('Ing', 'Circuitos', 'Ingeniero', 3, 10);


