package Grupo1.BackEndG1CP2.security.enums;

public enum RolNombre {
	
	ROLE_ADMIN, 
	ROLE_ESTUDIANTE, 
	ROLE_DOCENTE,
	ROLE_TUTORACADEMICO,
	ROLE_TUTOREMPRESARIAL,
	ROLE_RESPONSABLEPPP,
	ROLE_EMPLEADO,
	ROLE_CARRERA

}
